name: sepsesam api CI on debian 13

on: 
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: debian:trixie

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        apt-get update -y
        apt-get install -y curl gnupg

    - name: Add sesam repository key
      run: |
        mkdir -p /etc/apt/keyrings
        curl -fsSL https://download.sep.de/linux/repositories/debian/key.asc -o /etc/apt/keyrings/sesam.asc

    - name: Configure sesam apt sources
      run: echo "deb [signed-by=/etc/apt/keyrings/sesam.asc] https://download.sep.de/linux/repositories/debian/ trixie main" > /etc/apt/sources.list.d/sesam.list

    - name: Update apt sources
      run: apt-get update -y

    - name: Install sesam server
      env:
          DEBIAN_FRONTEND: noninteractive
      run: apt-get install -y --no-install-recommends sesam-srv python3 python3-pip

    - name: Install sepsesam module
      run: |
        python3 -m pip install requests --break-system-packages
        python3 -m pip install . --break-system-packages

    - name: Execute pyunit tests
      run: python3 -m unittest t/tests.py